monitor = int(input('Введи стоимость монитора: '))
system_block = int(input('Введи системного блока : '))
keyboard = int(input('Введи стоимость клавиатуры: '))
mouse = int(input('Введи стоимость мыши: '))
print()
print(f'Стоимость 1 монитора: {monitor};')
print(f'Стоимость 1 системного блока: {system_block};')
print(f'Стоимость 1 клавиатуры: {keyboard};')
print(f'Стоимость 1 мыши: {mouse};')
print(f'Стоимость 3 компьютеров: {(monitor + keyboard + mouse + system_block) * 3}.')
