print('Абсолютная сумма')
print()
a1 = float(input('Введи первое число: '))
a2 = float(input('Введи второе число: '))
a3 = float(input('Введи третье число: '))
a4 = float(input('Введи четвёртое число: '))
a5 = float(input('Введи пятое число: '))
a1, a2, a3, a4, a5 = abs(a1), abs(a2), abs(a3), abs(a4), abs(a5)
print(a1 + a2 + a3 + a4 + a5)
